<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="anythink">
	<title>Dashboard</title>
	<link href="static/css/bootstrap.min.css" rel="stylesheet">
	<link href="static/css/bootstrap-switch.min.css" rel="stylesheet">
	<link href="static/css/dashboard.css" rel="stylesheet">
</head>
<body style="background-color:  #f1f1f1">
<main id="content" role="main">
	<div id="content" class="bs-docs-header">
		<div class="container">
			<h1><img src="static/img/dashboard.png"> SyncRadio <small>v1.0</small></h1>
		</div>
	</div>
	<hr size="1">
	<div class="container">
		<div class="col-lg-3">
			<h2>服务状态  </h2>
			<ul class="list-group">
				<li class="list-group-item clearfix">
					<div class="pull-left">
						<img class="img-rounded" style="max-width: 100px" id="cover">
						<!--<span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>-->
					</div>
					<div class="pull-left" style="margin-left: 10px">
						<div id="play_title"></div>
						<div id="play_album"></div>
						<div id="play_artist"></div>
					</div>

				</li>
				<li class="list-group-item" id="server_status">正在连接</li>
				<li class="list-group-item">
				</li>
				<li class="list-group-item"></li>
			</ul>
		</div>
		<div id="console"></div>
		<div class="col-lg-3">
			<h2>播放列表 <a href="" class="btn btn-info btn-sm pull-right">添加列表</a> </h2>
			<ul class="list-group">
				<li class="list-group-item"></li>
				<li class="list-group-item">
				</li>
				<li class="list-group-item"></li>
			</ul>
		</div>

		<div class="col-lg-3">
			<h2>播控设置</h2>
			<div class="list-group">

			</div>
			<ul class="list-group">
				<li class="list-group-item">切歌 <input id="cut_music" type="checkbox" /></li>
				<li class="list-group-item">随机播放 <input id="play_random"  type="checkbox"/>
				</li>
				<li class="list-group-item">列表循环 <input id="play_loop"  type="checkbox"/>
				</li>
			</ul>
		</div>
		<div class="col-lg-3">
			<h2>点歌设置</h2>
			<div class="list-group">
			</div>
			<ul class="list-group">
				<li class="list-group-item"> 点歌功能 <input id="select_song"  type="checkbox" /></li>
				<li class="list-group-item">随机播放  <input id="select_song_random" type="checkbox" /></li>
				<li class="list-group-item">点歌间隔 <input type="number" id="select_song_rate" style="width: 105px">秒</li>
			</ul>
		</div>
	</div>
</main>
<footer class="bs-docs-footer">
	<div class="container">
		<p>Code licensed under <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License, Version 2.0</a>
			<br>Created by <a href="https://github.com/anythink-wx/syncRadio" target="_blank">anythink</a>
		</p>
	</div>
</footer>
<script src="static/js/jquery-1.11.1.min.js"></script>
<script src="static/js/bootstrap.min.js"></script>
<script src="static/js/bootstrap-switch.min.js"></script>
<script>
	var ws = new WebSocket('ws://<?=$server;?>');
	var isConnect = 0;
	ws.onopen = function(evt){
		$('#server_status').html('已连接');
		isConnect=1;
		ws.send('{"act":"sync"}');
	};
	ws.onmessage = function(evt){
		console.log(evt.data);
		var res = eval('(' + evt.data + ')');
		console.log(res);
		if(res.act =='sync'){
			$('#cover').attr('src',res.data.cover);
			$('#play_title').html(res.data.title);
			$('#play_album').html(res.data.album);
			$('#play_artist').html(res.data.artist);
		}
	};
	ws.onclose = function(evt){
		$('#server_status').html('已停止');
	};
	ws.onerror = function(evt){
		$('#server_status').html('已停止');
	}
	console.log(ws);
	$(function(argument) {



		$('[type="checkbox"]').bootstrapSwitch();
		$.ajax({
			url: '/admin?ajax=config',
			success: function (res) {
				if (res.code == 0) {
					$('#play_loop').bootstrapSwitch('state', res.body.play.loop, true);
					$('#play_random').bootstrapSwitch('state', res.body.play.random, true);
					$('#select_song').bootstrapSwitch('state', res.body.song.select_song, true);
					$('#select_song_random').bootstrapSwitch('state', res.body.song.random, true);
					$('#select_song_rate').val(res.body.song.select_song_rate);
				} else {
					alert(res.message);
				}
			},
			error:function(){
				alert('无法获取配置信息，请刷新页面');
			},
			dataType: 'json'
		});

		$('#cut_music').on('switchChange.bootstrapSwitch', function (e, data) {
			$.get('/admin?ajax=config&controller=cut',function(res){
				if(isConnect){
					ws.send('{"act":"sync"}');
				}
				setTimeout(function(){
					$('#cut_music').bootstrapSwitch('state',false, true);
				},1000);
			});
		});

		$('#play_random').on('switchChange.bootstrapSwitch', function (e, data) {
			$.get('/admin?ajax=config&controller=play_random&switch='+data);
		});

		$('#play_loop').on('switchChange.bootstrapSwitch', function (e, data) {
			$.get('/admin?ajax=config&controller=play_loop&switch='+data);
		});

		$('#select_song').on('switchChange.bootstrapSwitch', function (e, data) {
			$.get('/admin?ajax=config&controller=select_song&switch='+data);
		});

		$('#select_song_random').on('switchChange.bootstrapSwitch', function (e, data) {
			$.get('/admin?ajax=config&controller=select_song_random&switch='+data);
		});
		$('#select_song_rate').change(function(res){
			$.get('/admin?ajax=config&controller=select_song_rate&switch='+$(this).val());
		});




	})
</script>
</body>
</html>