<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>电台已关闭</title>
	<meta name="copyright" content="(c)2015 xi@anythink.com.cn"/>
	<meta name="author" content="anythink" />
</head>
<body style="background-color: #f1f1f1">
	<div style="margin-top: 180px">
		<p align="center"><img src="static/img/stop.png"></p>
		<div style="width: 280px; margin: 0px auto;">
			<marquee  scrollAmount="6">
				<p align="center" style="font-size: 28px;">服务离线，请稍后再试 | The Service is shutdown. Please try later</p>
			</marquee>
		</div>
	</div>
</body>
</html>